# Generated by Django 6.0.2 on 2026-02-15 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_support_thread_user_last_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasesImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('running', 'В процессе'), ('success', 'Завершён'), ('error', 'Ошибка')], default='running', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Результат или текст ошибки.')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bases_import_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Импорт баз',
                'verbose_name_plural': 'Импорты баз',
                'ordering': ['-created_at'],
            },
        ),
    ]
