# Generated by Django 6.0.2 on 2026-02-15 22:39

from django.db import migrations, models


def backfill_normalized_contact(apps, schema_editor):
    from core.lead_utils import normalize_lead_contact
    Lead = apps.get_model("core", "Lead")
    batch = []
    for lead in Lead.objects.iterator():
        lead.normalized_contact = normalize_lead_contact(lead.raw_contact or "")
        batch.append(lead)
        if len(batch) >= 500:
            Lead.objects.bulk_update(batch, ["normalized_contact"])
            batch = []
    if batch:
        Lead.objects.bulk_update(batch, ["normalized_contact"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_bases_import_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='normalized_contact',
            field=models.CharField(blank=True, db_index=True, help_text='Нормализованный контакт для проверки дубликатов по всей базе (@user→user, ссылки без протокола).', max_length=255),
        ),
        migrations.RunPython(backfill_normalized_contact, noop),
    ]
