# Generated by Django 6.0.2 on 2026-02-16 18:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_media_storage_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lead_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Дата лида (когда пользователь относит отчёт). По умолчанию — сегодня.'),
        ),
    ]
