# Generated by Django 6.0.2 on 2026-02-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_lead_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='needs_team_contact',
            field=models.BooleanField(default=False, help_text='Пометка «Связаться самим» — команда должна связаться с контактом.'),
        ),
    ]
