# Generated by Django 6.0.2 on 2026-02-22 11:39

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_needs_team_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('example_video', models.FileField(blank=True, help_text='Видео-пример идеального отчёта. Загрузите MP4/MOV/WEBM.', null=True, upload_to=core.models.site_settings_upload_to)),
                ('example_video_description', models.CharField(blank=True, default='Посмотрите пример идеального видео-отчёта', help_text='Текст ссылки на пример видео.', max_length=500)),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
