# Generated by Django 6.0.2 on 2026-02-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_site_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='auto_approve_users',
            field=models.BooleanField(default=False, help_text='Автоматически одобрять новых пользователей при регистрации.'),
        ),
    ]
