# Generated by Django 6.0.2 on 2026-02-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_auto_approve_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='ss_admin_status',
            field=models.CharField(blank=True, choices=[('rejected', 'Отказ'), ('in_progress', 'В работе'), ('meeting', 'Встреча')], help_text='Статус для самостоятельного админа (только одобренные СС-лиды).', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Пользователь'), ('support', 'Поддержка'), ('admin', 'Администратор'), ('standalone_admin', 'Самостоятельный админ')], default='user', help_text='Роль в системе (права доступа).', max_length=20),
        ),
    ]
