# Generated by Django 6.0.2 on 2026-02-24 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_add_standalone_admin_and_ss_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadReviewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('approved', 'Одобрено'), ('rejected', 'Отклонено'), ('rework', 'На доработку')], max_length=20)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_review_logs', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to='core.lead')),
            ],
            options={
                'verbose_name': 'Событие модерации лида',
                'verbose_name_plural': 'События модерации лидов',
            },
        ),
    ]
