# Generated by Django 6.0.2 on 2026-02-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_backfill_lead_review_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Можно ли контакт выдавать пользователям.'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Одобрен'), ('rejected', 'Отклонён'), ('rework', 'На доработке')], db_index=True, default='pending', help_text='Статус модерации лида.', max_length=20),
        ),
    ]
