# Generated by Django 6.0.2 on 2026-03-01 19:15

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_worker_subsystem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerreport',
            name='attachment',
            field=models.FileField(blank=True, help_text='Скриншот/видео подтверждения.', null=True, upload_to=core.models.worker_report_upload_to),
        ),
    ]
