# Generated by Django 6.0.2 on 2026-03-10 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_partner_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadassignment',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='partnerearning',
            name='lead',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_earning', to='core.lead'),
        ),
        migrations.AlterField(
            model_name='workerreport',
            name='standalone_admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_worker_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workerreport',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workerselflead',
            name='standalone_admin',
            field=models.ForeignKey(limit_choices_to={'role': 'standalone_admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_worker_self_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workerselflead',
            name='worker',
            field=models.ForeignKey(limit_choices_to={'role': 'worker'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='self_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workerwithdrawalrequest',
            name='standalone_admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_withdrawals_to_process', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workerwithdrawalrequest',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_withdrawal_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
