# Generated by Django 6.0.2 on 2026-03-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_self_lead_reward_150'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance_admin_earnings_offset',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Коррекция заработка при смене ставки (руб.).', max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='balance_admin_rate',
            field=models.DecimalField(decimal_places=2, default=5, help_text='Ставка баланс-админа за одобренный лид (руб.).', max_digits=6),
        ),
    ]
