# Generated by Django 6.0.2 on 2026-03-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_balance_admin_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadreviewlog',
            name='balance_admin_rate_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ставка баланс-админа на момент одобрения (руб.). NULL = старая ставка 5 руб.', max_digits=6, null=True),
        ),
    ]
