# Generated by Django 6.0.2 on 2026-03-26 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_balance_admin_rate_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='partner_rate',
            field=models.PositiveIntegerField(default=10, help_text='Ставка партнёра (руб.) за каждый одобренный лид реферала.'),
        ),
    ]
