# Generated by Django 6.0.2 on 2026-03-26 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_partner_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='DozhimIssuedLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dozhim_issues', to='core.lead')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dozhim_issued_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Выданный лид для дожима',
                'verbose_name_plural': 'Выданные лиды для дожима',
                'unique_together': {('user', 'lead')},
            },
        ),
    ]
