# Generated by Django 6.0.2 on 2026-03-26 13:35

from django.db import migrations


def create_dozhim_leadtype(apps, schema_editor):
    LeadType = apps.get_model("core", "LeadType")
    LeadType.objects.get_or_create(slug="dozhim", defaults={"name": "Дожим", "order": 999})


def remove_dozhim_leadtype(apps, schema_editor):
    LeadType = apps.get_model("core", "LeadType")
    LeadType.objects.filter(slug="dozhim").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_dozhim_issued_lead'),
    ]

    operations = [
        migrations.RunPython(create_dozhim_leadtype, remove_dozhim_leadtype),
    ]
