# Generated by Django 6.0.2 on 2026-03-30 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_dozhim_leadtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerlink',
            name='ref_reward',
            field=models.PositiveIntegerField(default=20, help_text='Ставка рефу за одобренный лид (руб.). Партнёр получает 40 - ref_reward.'),
        ),
        migrations.AddField(
            model_name='user',
            name='partner_link',
            field=models.ForeignKey(blank=True, help_text='Реферальная ссылка, по которой зарегистрировался пользователь (для affiliate-ставки).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_users', to='core.partnerlink'),
        ),
        migrations.AlterField(
            model_name='partnerlink',
            name='partner',
            field=models.ForeignKey(limit_choices_to={'role__in': ['partner', 'affiliate']}, on_delete=django.db.models.deletion.CASCADE, related_name='partner_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='partner_owner',
            field=models.ForeignKey(blank=True, help_text='Партнёр, привлёкший этого пользователя.', limit_choices_to={'role__in': ['partner', 'affiliate']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Пользователь'), ('support', 'Поддержка'), ('admin', 'Админ по отчётам'), ('main_admin', 'Главный админ'), ('standalone_admin', 'Самостоятельный админ'), ('balance_admin', 'Баланс‑админ'), ('worker', 'Исполнитель'), ('partner', 'Партнёр'), ('affiliate', 'Партнёрка')], default='user', help_text='Роль в системе (права доступа).', max_length=20),
        ),
    ]
