# Generated by Django 6.0.2 on 2026-03-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_worker_self_lead_reward_40'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dozhim_balance',
            field=models.IntegerField(default=0, help_text='Баланс пользователя за Отдел дожима (руб.).'),
        ),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.IntegerField(default=0, help_text='Баланс пользователя за Отдел поиска (руб.).'),
        ),
    ]
