# Generated by Django 6.0.2 on 2026-03-30 19:57

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_split_dozhim_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, default=core.models.search_link_code, help_text='Уникальный код ссылки (/s/<code>/).', max_length=32, unique=True)),
                ('lead_name', models.CharField(help_text='Имя/ник лида (для OG-тегов и персонализации).', max_length=200)),
                ('bot_username', models.CharField(blank=True, help_text='Username бота из пула (без @).', max_length=64)),
                ('bot_started', models.BooleanField(db_index=True, default=False, help_text='Лид запустил бота (подтверждено вебхуком).')),
                ('bot_started_at', models.DateTimeField(blank=True, help_text='Когда лид запустил бота.', null=True)),
                ('telegram_id', models.BigIntegerField(blank=True, help_text='Telegram ID лида (из вебхука).', null=True)),
                ('user', models.ForeignKey(help_text='Менеджер, создавший ссылку.', on_delete=django.db.models.deletion.CASCADE, related_name='search_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SearchLink',
                'verbose_name_plural': 'SearchLinks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead_date', models.DateField(default=django.utils.timezone.now, help_text='Дата отчёта.')),
                ('attachment', models.FileField(blank=True, help_text='Скриншот/видео подтверждения.', null=True, upload_to=core.models.search_report_upload_to)),
                ('comment', models.TextField(blank=True, help_text='Комментарий менеджера.')),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Одобрен'), ('rejected', 'Отклонён'), ('rework', 'На доработке')], db_index=True, default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('rework_comment', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_search_reports', to=settings.AUTH_USER_MODEL)),
                ('search_link', models.OneToOneField(help_text='К какому SearchLink привязан отчёт.', on_delete=django.db.models.deletion.CASCADE, related_name='report', to='core.searchlink')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Отчёт SearchLink',
                'verbose_name_plural': 'Отчёты SearchLink',
                'ordering': ['-created_at'],
            },
        ),
    ]
