# Generated by Django 6.0.2 on 2026-03-31 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_searchlink_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadassignment',
            name='refused',
            field=models.BooleanField(db_index=True, default=False, help_text='Лид отказался, нужно связаться Артёму.'),
        ),
        migrations.AddField(
            model_name='leadassignment',
            name='refused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
