# Generated by Django 6.0.2 on 2026-03-31 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_assignment_refused'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerlink',
            name='partner',
            field=models.ForeignKey(limit_choices_to={'role__in': ['partner', 'user']}, on_delete=django.db.models.deletion.CASCADE, related_name='partner_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='partner_owner',
            field=models.ForeignKey(blank=True, help_text='Партнёр, привлёкший этого пользователя.', limit_choices_to={'role__in': ['partner', 'user']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Пользователь'), ('support', 'Поддержка'), ('admin', 'Админ по отчётам'), ('main_admin', 'Главный админ'), ('standalone_admin', 'Самостоятельный админ'), ('balance_admin', 'Баланс‑админ'), ('worker', 'Исполнитель'), ('partner', 'Партнёр')], default='user', help_text='Роль в системе (права доступа).', max_length=20),
        ),
    ]
