# Generated by Django 6.0.2 on 2026-04-01 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_remove_affiliate_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(default='balance', help_text='Какой баланс: balance или dozhim_balance.', max_length=20)),
                ('old_value', models.IntegerField(help_text='Баланс до операции.')),
                ('new_value', models.IntegerField(help_text='Баланс после операции.')),
                ('delta', models.IntegerField(help_text='Изменение (+ или -).')),
                ('reason', models.CharField(help_text='Причина изменения.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, help_text='Кто выполнил действие (админ, система).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balance_actions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Лог баланса',
                'verbose_name_plural': 'Логи баланса',
                'ordering': ['-created_at'],
            },
        ),
    ]
