# Generated by Django 6.0.2 on 2026-04-05 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_balance_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_accredited',
            field=models.BooleanField(default=False, help_text='Аккредитирован (галочка для вывода средств).'),
        ),
    ]
