# Generated by Django 6.0.2 on 2026-04-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_user_is_accredited'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchlink',
            name='creator_ip',
            field=models.GenericIPAddressField(blank=True, help_text='IP менеджера при создании ссылки.', null=True),
        ),
        migrations.AddField(
            model_name='searchlink',
            name='self_click',
            field=models.BooleanField(db_index=True, default=False, help_text='IP менеджера совпал с IP посетителя — подозрение на накрутку.'),
        ),
        migrations.AddField(
            model_name='searchlink',
            name='visitor_ip',
            field=models.GenericIPAddressField(blank=True, help_text='IP посетителя при клике на лендинг.', null=True),
        ),
    ]
