# Generated by Django 6.0.2 on 2026-04-13 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_search_link_ip_protection'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchreport',
            name='raw_contact',
            field=models.CharField(blank=True, help_text='Контакт / ссылка на клиента.', max_length=500),
        ),
    ]
