# Generated by Django 6.0.2 on 2026-04-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_search_report_raw_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='smz_fio',
            field=models.CharField(blank=True, help_text='ФИО для СМЗ.', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='smz_not_self',
            field=models.BooleanField(default=False, help_text='Приём не на себя (чужие реквизиты).'),
        ),
        migrations.AddField(
            model_name='user',
            name='smz_reject_reason',
            field=models.TextField(blank=True, help_text='Причина отклонения СМЗ.'),
        ),
        migrations.AddField(
            model_name='user',
            name='smz_status',
            field=models.CharField(choices=[('none', 'Не подано'), ('pending', 'На проверке'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='none', help_text='Статус верификации СМЗ.', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='smz_submitted_at',
            field=models.DateTimeField(blank=True, help_text='Дата подачи заявки на СМЗ.', null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='receipt',
            field=models.FileField(blank=True, help_text='Чек СМЗ (скриншот).', null=True, upload_to='receipts/'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='receipt_checked',
            field=models.BooleanField(default=False, help_text='Чек проверен админом.'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='receipt_uploaded_at',
            field=models.DateTimeField(blank=True, help_text='Дата загрузки чека.', null=True),
        ),
    ]
