# Generated by Django 6.0.2 on 2026-04-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_smz_verification_receipts'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='receipt_reject_reason',
            field=models.TextField(blank=True, help_text='Причина отклонения чека.'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='receipt_status',
            field=models.CharField(choices=[('none', 'Нет чека'), ('pending', 'На проверке'), ('approved', 'Одобрен'), ('rejected', 'Отклонён')], default='none', help_text='Статус проверки чека.', max_length=20),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='receipt_checked',
            field=models.BooleanField(default=False, help_text='Чек проверен админом (deprecated, use receipt_status).'),
        ),
    ]
