# Generated by Django 6.0.2 on 2026-04-14 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_receipt_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerearning',
            name='search_report',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_earning', to='core.searchreport'),
        ),
        migrations.AddField(
            model_name='user',
            name='ref_searchlink_enabled',
            field=models.BooleanField(default=False, help_text='Разрешён ли SearchLink для реферала (включается менеджером-рефовладельцем).'),
        ),
        migrations.AddField(
            model_name='user',
            name='ref_searchlink_manager_cut',
            field=models.PositiveIntegerField(default=30, help_text='Доля менеджера (руб.) с одобренного SearchLink-отчёта реферала. Реферал получает 100 - cut.'),
        ),
    ]
