# Generated by Django 6.0.2 on 2026-04-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_ref_searchlink_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ref_lead_reward',
            field=models.PositiveIntegerField(blank=True, help_text='Ставка рефералу за одобренный лид (руб.). Если задано — перекрывает ставку из PartnerLink.', null=True),
        ),
    ]
