# Generated by Django 6.0.2 on 2026-04-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_ref_lead_reward_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchlink',
            name='display_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='Сквозной номер (общая нумерация с Lead).', null=True, unique=True),
        ),
    ]
