# Generated by Django 6.0.2 on 2026-08-17 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_invited_by'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='callreport',
            new_name='core_callre_status_dc4e4e_idx',
            old_name='core_callre_status_d6cf2a_idx',
        ),
        migrations.RenameIndex(
            model_name='manualsearchclaim',
            new_name='core_manual_user_id_809718_idx',
            old_name='core_manual_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='manualsearchclaim',
            new_name='core_manual_normali_68dc5b_idx',
            old_name='core_manual_norm_idx',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='zvonok_campaign_id_10min',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='zvonok_campaign_id_1h',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='zvonok_campaign_id_now',
        ),
        migrations.AddField(
            model_name='user',
            name='fraud_blocked',
            field=models.BooleanField(db_index=True, default=False, help_text='Выплаты заблокированы за накрутку (самостарты своих ссылок).'),
        ),
        migrations.AddField(
            model_name='user',
            name='fraud_note',
            field=models.CharField(blank=True, default='', help_text='Причина блокировки выплат.', max_length=255),
        ),
        migrations.AlterField(
            model_name='manualsearchclaim',
            name='matched_manual_claim',
            field=models.ForeignKey(blank=True, help_text='Предыдущий ManualSearchClaim с тем же клиентом (если применимо).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflicts', to='core.manualsearchclaim'),
        ),
        migrations.AlterField(
            model_name='manualsearchclaim',
            name='matched_search_link',
            field=models.ForeignKey(blank=True, help_text='Существующая SearchLink с этим клиентом, из-за которой claim отклонён (если применимо).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_claims_conflicting', to='core.searchlink'),
        ),
        migrations.AlterField(
            model_name='searchlink',
            name='bot_username',
            field=models.CharField(blank=True, help_text='Для TG — username бота из пула (без @). Для VK — screen_name community.', max_length=64),
        ),
        migrations.AlterField(
            model_name='searchlink',
            name='platform',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('vk', 'VK'), ('both', 'Универсальный (TG + VK)')], db_index=True, default='telegram', help_text='Платформа бота: Telegram или VK.', max_length=16),
        ),
        migrations.AlterField(
            model_name='searchreport',
            name='normalized_contact',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Нормализованный raw_contact для поиска дубликатов (telegram:user, vk:id, +7XXXXXXXXXX, ig:user, ok:id и т.д.).', max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='can_create_call_reports',
            field=models.BooleanField(db_index=True, default=False, help_text='(deprecated) Используйте can_create_group_reports.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ref_searchlink_enabled',
            field=models.BooleanField(default=True, help_text='Разрешён ли SearchLink для реферала. По умолчанию включено для всех новых рефералов. (legacy, не используется в UI)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ref_searchlink_manager_cut',
            field=models.PositiveIntegerField(default=50, help_text='(legacy, не используется) Доля менеджера-рефовладельца с SearchLink-отчёта реферала.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает одобрения'), ('approved', 'Одобрен'), ('banned', 'Заблокирован')], db_index=True, default='pending', help_text='Статус модерации пользователя.', max_length=20),
        ),
    ]
