# Generated by Django 6.0.2 on 2026-08-17 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_fraud_blocked'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmzBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(help_text='ФИО как ввёл пользователь.', max_length=255)),
                ('fio_norm', models.CharField(db_index=True, help_text='Нормализованное ФИО для сравнения.', max_length=255, unique=True)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smz_blocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заблокированное ФИО (СМЗ)',
                'verbose_name_plural': 'Заблокированные ФИО (СМЗ)',
                'ordering': ['-created_at'],
            },
        ),
    ]
