# Generated by Django 6.0.2 on 2026-08-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_smz_blacklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='old_balance',
            field=models.IntegerField(default=0, help_text='Баланс за период до 17.08.2026 (отдельный вывод).'),
        ),
    ]
